import type { FontFamily } from "~/lib/types";

export interface FontDef {
  value: FontFamily;
  label: string;
  desc: string;
  cssVar: string;
  category: "sans" | "serif" | "mono" | "display" | "handwriting" | "other";
}

export const FONTS: FontDef[] = [
  { value: "advent-pro", label: "Advent Pro", desc: "geometric sans", cssVar: "var(--font-advent-pro)", category: "sans" },
  { value: "alfa-slab-one", label: "Alfa Slab One", desc: "slab display", cssVar: "var(--font-alfa-slab-one)", category: "display" },
  { value: "anonymous-pro", label: "Anonymous Pro", desc: "typewriter mono", cssVar: "var(--font-anonymous-pro)", category: "mono" },
  { value: "archivo", label: "Archivo", desc: "grotesque sans", cssVar: "var(--font-archivo)", category: "sans" },
  { value: "asap", label: "Asap", desc: "geometric sans", cssVar: "var(--font-asap)", category: "sans" },
  { value: "atkinson-hyperlegible", label: "Atkinson Hyperlegible", desc: "dyslexic-friendly", cssVar: "var(--font-atkinson-hyperlegible)", category: "sans" },
  { value: "baloo-2", label: "Baloo 2", desc: "rounded sans", cssVar: "var(--font-baloo-2)", category: "sans" },
  { value: "barlow", label: "Barlow", desc: "neo-grotesk sans", cssVar: "var(--font-barlow)", category: "sans" },
  { value: "bitter", label: "Bitter", desc: "slab serif", cssVar: "var(--font-bitter)", category: "serif" },
  { value: "bricolage-grotesque", label: "Bricolage Grotesque", desc: "variable grotesk", cssVar: "var(--font-bricolage-grotesque)", category: "sans" },
  { value: "cabin", label: "Cabin", desc: "humanist sans", cssVar: "var(--font-cabin)", category: "sans" },
  { value: "cal-sans", label: "Cal Sans", desc: "geometric display", cssVar: "var(--font-cal-sans)", category: "display" },
  { value: "cascadia-code", label: "Cascadia Code", desc: "microsoft mono", cssVar: "var(--font-cascadia-code)", category: "mono" },
  { value: "caveat", label: "Caveat", desc: "handwriting", cssVar: "var(--font-caveat)", category: "handwriting" },
  { value: "chivo", label: "Chivo", desc: "grotesque sans", cssVar: "var(--font-chivo)", category: "sans" },
  { value: "comic-neue", label: "Comic Sans", desc: "casual cursive", cssVar: "var(--font-comic-neue)", category: "handwriting" },
  { value: "commit-mono", label: "Commit Mono", desc: "neutral mono", cssVar: "var(--font-commit-mono)", category: "mono" },
  { value: "comfortaa", label: "Comfortaa", desc: "rounded sans", cssVar: "var(--font-comfortaa)", category: "sans" },
  { value: "coming-soon", label: "Coming Soon", desc: "handwriting", cssVar: "var(--font-coming-soon)", category: "handwriting" },
  { value: "courier-prime", label: "Courier Prime", desc: "courier variant", cssVar: "var(--font-courier-prime)", category: "mono" },
  { value: "crimson-pro", label: "Crimson Pro", desc: "old-style serif", cssVar: "var(--font-crimson-pro)", category: "serif" },
  { value: "dancing-script", label: "Dancing Script", desc: "script", cssVar: "var(--font-dancing-script)", category: "handwriting" },
  { value: "dm-sans", label: "DM Sans", desc: "geometric sans", cssVar: "var(--font-dm-sans)", category: "sans" },
  { value: "domine", label: "Domine", desc: "transitional serif", cssVar: "var(--font-domine)", category: "serif" },
  { value: "exo-2", label: "Exo 2", desc: "geometric sans", cssVar: "var(--font-exo-2)", category: "sans" },
  { value: "figtree", label: "Figtree", desc: "geometric sans", cssVar: "var(--font-figtree)", category: "sans" },
  { value: "fira-code", label: "Fira Code", desc: "monospace ligatures", cssVar: "var(--font-fira-code)", category: "mono" },
  { value: "fira-sans", label: "Fira Sans", desc: "humanist sans", cssVar: "var(--font-fira-sans)", category: "sans" },
  { value: "fredoka", label: "Fredoka", desc: "rounded sans", cssVar: "var(--font-fredoka)", category: "sans" },
  { value: "geist", label: "Geist", desc: "variable sans", cssVar: "var(--font-geist)", category: "sans" },
  { value: "geist-mono", label: "Geist Mono", desc: "variable mono", cssVar: "var(--font-geist-mono)", category: "mono" },
  { value: "gelasio", label: "Gelasio", desc: "Georgia variant", cssVar: "var(--font-gelasio)", category: "serif" },
  { value: "google-sans", label: "Google Sans", desc: "google sans", cssVar: "var(--font-google-sans)", category: "sans" },
  { value: "ibm-plex-mono", label: "IBM Plex Mono", desc: "ibm mono", cssVar: "var(--font-ibm-plex-mono)", category: "mono" },
  { value: "ibm-plex-sans", label: "IBM Plex Sans", desc: "ibm sans", cssVar: "var(--font-ibm-plex-sans)", category: "sans" },
  { value: "inconsolata", label: "Inconsolata", desc: "condensed mono", cssVar: "var(--font-inconsolata)", category: "mono" },
  { value: "inter", label: "Inter", desc: "variable sans", cssVar: "var(--font-inter)", category: "sans" },
  { value: "itim", label: "Itim", desc: "casual sans", cssVar: "var(--font-itim)", category: "sans" },
  { value: "iosevka", label: "Iosevka", desc: "code ligature mono", cssVar: "var(--font-iosevka)", category: "mono" },
  { value: "jetbrains-mono", label: "JetBrains Mono", desc: "code mono", cssVar: "var(--font-jetbrains-mono)", category: "mono" },
  { value: "josefin-sans", label: "Josefin Sans", desc: "geometric sans", cssVar: "var(--font-josefin-sans)", category: "sans" },
  { value: "karla", label: "Karla", desc: "grotesque sans", cssVar: "var(--font-karla)", category: "sans" },
  { value: "lato", label: "Lato", desc: "humanist sans", cssVar: "var(--font-lato)", category: "sans" },
  { value: "lexend", label: "Lexend", desc: "readability sans", cssVar: "var(--font-lexend)", category: "sans" },
  { value: "lobster", label: "Lobster", desc: "display script", cssVar: "var(--font-lobster)", category: "display" },
  { value: "lora", label: "Lora", desc: "calligraphy serif", cssVar: "var(--font-lora)", category: "serif" },
  { value: "manrope", label: "Manrope", desc: "grotesque sans", cssVar: "var(--font-manrope)", category: "sans" },
  { value: "merriweather", label: "Merriweather", desc: "sturdy serif", cssVar: "var(--font-merriweather)", category: "serif" },
  { value: "mona-sans", label: "Mona Sans", desc: "variable sans", cssVar: "var(--font-mona-sans)", category: "sans" },
  { value: "montserrat", label: "Montserrat", desc: "geometric sans", cssVar: "var(--font-montserrat)", category: "sans" },
  { value: "noto-sans", label: "Noto Sans", desc: "universal sans", cssVar: "var(--font-noto-sans)", category: "sans" },
  { value: "noto-serif", label: "Noto Serif", desc: "universal serif", cssVar: "var(--font-noto-serif)", category: "serif" },
  { value: "nunito", label: "Nunito", desc: "rounded sans", cssVar: "var(--font-nunito)", category: "sans" },
  { value: "nunito-sans", label: "Nunito Sans", desc: "rounded sans", cssVar: "var(--font-nunito-sans)", category: "sans" },
  { value: "opendyslexic", label: "OpenDyslexic", desc: "dyslexic-friendly", cssVar: "var(--font-opendyslexic)", category: "sans" },
  { value: "open-sans", label: "Open Sans", desc: "humanist sans", cssVar: "var(--font-open-sans)", category: "sans" },
  { value: "oswald", label: "Oswald", desc: "condensed sans", cssVar: "var(--font-oswald)", category: "sans" },
  { value: "outfit", label: "Outfit", desc: "geometric sans", cssVar: "var(--font-outfit)", category: "sans" },
  { value: "oxygen", label: "Oxygen", desc: "humanist sans", cssVar: "var(--font-oxygen)", category: "sans" },
  { value: "pacifico", label: "Pacifico", desc: "brush script", cssVar: "var(--font-pacifico)", category: "handwriting" },
  { value: "petrona", label: "Petrona", desc: "old-style serif", cssVar: "var(--font-petrona)", category: "serif" },
  { value: "playfair-display", label: "Playfair Display", desc: "didone serif", cssVar: "var(--font-playfair-display)", category: "serif" },
  { value: "plus-jakarta-sans", label: "Plus Jakarta Sans", desc: "geometric sans", cssVar: "var(--font-plus-jakarta-sans)", category: "sans" },
  { value: "poppins", label: "Poppins", desc: "geometric sans", cssVar: "var(--font-poppins)", category: "sans" },
  { value: "pt-sans", label: "PT Sans", desc: "humanist sans", cssVar: "var(--font-pt-sans)", category: "sans" },
  { value: "pt-serif", label: "PT Serif", desc: "transitional serif", cssVar: "var(--font-pt-serif)", category: "serif" },
  { value: "quicksand", label: "Quicksand", desc: "rounded sans", cssVar: "var(--font-quicksand)", category: "sans" },
  { value: "raleway", label: "Raleway", desc: "elegant sans", cssVar: "var(--font-raleway)", category: "sans" },
  { value: "red-hat-display", label: "Red Hat Display", desc: "display sans", cssVar: "var(--font-red-hat-display)", category: "display" },
  { value: "red-hat-mono", label: "Red Hat Mono", desc: "mono", cssVar: "var(--font-red-hat-mono)", category: "mono" },
  { value: "roboto", label: "Roboto", desc: "neo-grotesk sans", cssVar: "var(--font-roboto)", category: "sans" },
  { value: "roboto-flex", label: "Roboto Flex", desc: "variable sans", cssVar: "var(--font-roboto-flex)", category: "sans" },
  { value: "roboto-mono", label: "Roboto Mono", desc: "mono", cssVar: "var(--font-roboto-mono)", category: "mono" },
  { value: "roboto-slab", label: "Roboto Slab", desc: "slab serif", cssVar: "var(--font-roboto-slab)", category: "serif" },
  { value: "rubik", label: "Rubik", desc: "rounded sans", cssVar: "var(--font-rubik)", category: "sans" },
  { value: "sarabun", label: "Sarabun", desc: "thai sans", cssVar: "var(--font-sarabun)", category: "sans" },
  { value: "shantell-sans", label: "Shantell Sans", desc: "handwriting sans", cssVar: "var(--font-shantell-sans)", category: "handwriting" },
  { value: "sora", label: "Sora", desc: "geometric sans", cssVar: "var(--font-sora)", category: "sans" },
  { value: "source-code-pro", label: "Source Code Pro", desc: "code mono", cssVar: "var(--font-source-code-pro)", category: "mono" },
  { value: "space-grotesk", label: "Space Grotesk", desc: "monospace-inspired", cssVar: "var(--font-space-grotesk)", category: "sans" },
  { value: "space-mono", label: "Space Mono", desc: "monospace", cssVar: "var(--font-space-mono)", category: "mono" },
  { value: "titillium-web", label: "Titillium Web", desc: "technical sans", cssVar: "var(--font-titillium-web)", category: "sans" },
  { value: "ubuntu", label: "Ubuntu", desc: "humanist sans", cssVar: "var(--font-ubuntu)", category: "sans" },
  { value: "ubuntu-mono", label: "Ubuntu Mono", desc: "mono", cssVar: "var(--font-ubuntu-mono)", category: "mono" },
  { value: "urbanist", label: "Urbanist", desc: "geometric sans", cssVar: "var(--font-urbanist)", category: "sans" },
  { value: "victor-mono", label: "Victor Mono", desc: "cursive mono", cssVar: "var(--font-victor-mono)", category: "mono" },
  { value: "work-sans", label: "Work Sans", desc: "variable sans", cssVar: "var(--font-work-sans)", category: "sans" },
];
