/** Common English word pool for the `words` source and as universal fallback. */
export const ENGLISH_COMMON: string[] = [
  "the","be","of","and","a","to","in","he","have","it","that","for","they","with",
  "as","not","on","she","at","by","this","we","you","do","but","from","or","which",
  "one","would","all","will","there","say","who","make","when","can","more","if",
  "no","man","out","other","so","what","time","up","go","about","than","into","could",
  "state","only","new","year","some","take","come","these","know","see","use","get",
  "like","then","first","any","work","now","may","such","give","over","think","most",
  "even","find","day","also","after","way","many","must","look","before","great",
  "back","through","long","where","much","should","well","people","down","own","just",
  "because","good","each","those","feel","seem","how","high","too","place","little",
  "world","very","still","nation","hand","old","life","tell","write","become","here",
  "show","house","both","between","need","mean","call","develop","under","last",
  "right","move","thing","general","school","never","same","another","begin","while",
  "number","part","turn","real","leave","might","want","point","form","off","child",
  "few","small","since","against","ask","late","home","interest","large","person",
  "end","open","public","follow","during","present","without","again","hold","govern",
  "around","possible","head","consider","word","program","problem","however","lead",
  "system","set","order","eye","plan","run","keep","face","fact","group","play",
  "stand","increase","early","course","change","help","line","light","water","money",
  "story","month","study","book","side","food","night","idea","whole","body","music",
  "color","stand","sun","question","fish","area","mark","dog","bird","supply","corner",
  "electric","hair","tree","farm","city","press","close","case","unit","power","town",
  "minute","voice","watch","range","ship","trade","field","rock","level","ground",
  "cold","notice","rest","sight","care","second","table","wind","paper","science",
  "air","door","product","black","white","fire","north","south","east","west","read",
  "live","far","near","build","earth","parent","island","week","thought","list",
  "quick","slow","strong","clear","dark","deep","done","easy","free","full","hard",
  "heavy","kind","less","long","loud","low","meant","near","open","past","plain",
  "poor","rich","short","soft","sure","tall","warm","wide","young","early","empty",
  "every","false","final","future","happy","human","important","local","modern",
  "natural","normal","personal","political","popular","public","recent","similar",
  "simple","single","social","special","standard","strict","sweet","thin","total",
  "true","usual","whole","wrong","answer","beginning","choice","computer","detail",
  "difference","effect","example","family","father","friend","history","hour",
  "information","job","letter","market","message","moment","morning","mother",
  "name","nothing","page","picture","reason","result","room","service","situation",
  "son","sound","space","teacher","term","test","today","together","tomorrow",
  "tonight","trouble","truth","woman","word","year","yesterday","always","enough",
  "often","perhaps","probably","quite","really","sometimes","soon","usually","yet",
  "again","almost","already","although","among","around","because","behind","below",
  "beneath","beside","beyond","during","except","inside","instead","near","outside",
  "toward","under","until","within","without","above","across","against","along",
];

/** Words used to probe the dictionary API — interesting definitions, common letters. */
export const DICT_PROBE_WORDS: string[] = [
  "ephemeral","serendipity","luminous","resilience","eloquent","petrichor",
  "wanderlust","solitude","nostalgia","mellifluous","ethereal","quintessential",
  "ineffable","epiphany","limerence","halcyon","susurrus","apricity","vellichor",
  "sonorous","iridescent","tranquil","vivacious","zenith","nebulous","aesthetic",
  "cascade","diligent","effervescent","flourish","gossamer","harbinger","incandescent",
  "juxtapose","kindle","labyrinth","meander","nuance","oblivion","paradigm","quiver",
  "reverie","silhouette","tangible","umbra","vertigo","whimsical","zephyr","aurora",
  "brisk","candor","demure","ebullient","fervent","glacial","hallowed","impeccable",
];
