import { Theme } from "./types";

export const STORAGE_KEY_SETTINGS = "zentype_settings";
export const STORAGE_KEY_HISTORY = "zentype_history";

export const WORDS_LIST = [
  "the",
  "be",
  "of",
  "and",
  "a",
  "to",
  "in",
  "he",
  "have",
  "it",
  "that",
  "for",
  "they",
  "with",
  "as",
  "not",
  "on",
  "she",
  "at",
  "by",
  "this",
  "we",
  "you",
  "do",
  "but",
  "from",
  "or",
  "which",
  "one",
  "would",
  "all",
  "will",
  "there",
  "say",
  "who",
  "make",
  "when",
  "can",
  "more",
  "if",
  "no",
  "man",
  "out",
  "other",
  "so",
  "what",
  "time",
  "up",
  "go",
  "about",
  "than",
  "into",
  "could",
  "state",
  "only",
  "new",
  "year",
  "some",
  "take",
  "come",
  "these",
  "know",
  "see",
  "use",
  "get",
  "like",
  "then",
  "first",
  "any",
  "work",
  "now",
  "may",
  "such",
  "give",
  "over",
  "think",
  "most",
  "even",
  "find",
  "day",
  "also",
  "after",
  "way",
  "many",
  "must",
  "look",
  "before",
  "great",
  "back",
  "through",
  "long",
  "where",
  "much",
  "should",
  "well",
  "people",
  "down",
  "own",
  "just",
  "because",
  "good",
  "each",
  "those",
  "feel",
  "seem",
  "how",
  "high",
  "too",
  "place",
  "little",
  "world",
  "very",
  "still",
  "nation",
  "hand",
  "old",
  "life",
  "tell",
  "write",
  "become",
  "here",
  "show",
  "house",
  "both",
  "between",
  "need",
  "mean",
  "call",
  "develop",
  "under",
  "last",
  "right",
  "move",
  "thing",
  "general",
  "school",
  "never",
  "same",
  "another",
  "begin",
  "while",
  "number",
  "part",
  "turn",
  "real",
  "leave",
  "might",
  "want",
  "point",
  "form",
  "off",
  "child",
  "few",
  "small",
  "since",
  "against",
  "ask",
  "late",
  "home",
  "interest",
  "large",
  "person",
  "end",
  "open",
  "public",
  "follow",
  "during",
  "present",
  "without",
  "again",
  "hold",
  "govern",
  "around",
  "possible",
  "head",
  "consider",
  "word",
  "program",
  "problem",
  "however",
  "lead",
  "system",
  "set",
  "order",
  "eye",
  "plan",
  "run",
  "keep",
  "face",
  "fact",
  "group",
  "play",
  "stand",
  "increase",
  "early",
  "course",
  "change",
  "help",
  "line",
];

export const THEMES: Theme[] = [
  {
    name: "serika_dark",
    bg: "#323437",
    text: "#d1d0c5",
    sub: "#646669",
    main: "#e2b714",
    caret: "#e2b714",
    error: "#ca4754",
  },
  {
    name: "carbon",
    bg: "#313131",
    text: "#f6f6f6",
    sub: "#616161",
    main: "#f66e0d",
    caret: "#f66e0d",
    error: "#e03131",
  },
  {
    name: "one_dark",
    bg: "#282c34",
    text: "#abb2bf",
    sub: "#5c6370",
    main: "#61afef",
    caret: "#528bff",
    error: "#e06c75",
  },
  {
    name: "matrix",
    bg: "#000000",
    text: "#00ff41",
    sub: "#003b00",
    main: "#008f11",
    caret: "#00ff41",
    error: "#da3333",
  },
  {
    name: "vaporwave",
    bg: "#1a0b2e",
    text: "#76e7cd",
    sub: "#4a2c6d",
    main: "#ff00d4",
    caret: "#ff00d4",
    error: "#ff2a2a",
  },
  {
    name: "dark_magic",
    bg: "#091f2c",
    text: "#a5b6c8",
    sub: "#445569",
    main: "#93e8d3",
    caret: "#93e8d3",
    error: "#e23434",
  },
  {
    name: "boulevard",
    bg: "#1f222e",
    text: "#c2c4cc",
    sub: "#4e5466",
    main: "#fab795",
    caret: "#fab795",
    error: "#ff5e5e",
  },
  {
    name: "bento",
    bg: "#2d394d",
    text: "#fffaf8",
    sub: "#4a5a75",
    main: "#ff7a90",
    caret: "#ff7a90",
    error: "#ee2a2a",
  },
  {
    name: "laser",
    bg: "#221b44",
    text: "#009999",
    sub: "#594a82",
    main: "#b82466",
    caret: "#009999",
    error: "#ff004c",
  },
  {
    name: "synthwave",
    bg: "#2b213a",
    text: "#b3b3b3",
    sub: "#4d4160",
    main: "#ff0090",
    caret: "#00fff5",
    error: "#ff2929",
  },
  {
    name: "cyberpunk",
    bg: "#000b1e",
    text: "#00f3ff",
    sub: "#575b70",
    main: "#fcee0a",
    caret: "#fcee0a",
    error: "#ff003c",
  },
  {
    name: "light",
    bg: "#ffffff",
    text: "#444444",
    sub: "#999999",
    main: "#00a8e8",
    caret: "#00a8e8",
    error: "#ff3333",
  },
  {
    name: "dracula",
    bg: "#282a36",
    text: "#f8f8f2",
    sub: "#6272a4",
    main: "#bd93f9",
    caret: "#bd93f9",
    error: "#ff5555",
  },
  {
    name: "nord",
    bg: "#2e3440",
    text: "#d8dee9",
    sub: "#4c566a",
    main: "#88c0d0",
    caret: "#88c0d0",
    error: "#bf616a",
  },
  {
    name: "gruvbox_dark",
    bg: "#282828",
    text: "#ebdbb2",
    sub: "#928374",
    main: "#fabd2f",
    caret: "#fabd2f",
    error: "#cc241d",
  },
  {
    name: "coffee",
    bg: "#ceb18d",
    text: "#2c241b",
    sub: "#7e6c58",
    main: "#141204",
    caret: "#141204",
    error: "#a32a2a",
  },
  {
    name: "miami_nights",
    bg: "#181818",
    text: "#e4609b",
    sub: "#47bac0",
    main: "#e4609b",
    caret: "#e4609b",
    error: "#fff500",
  },
  {
    name: "matcha_moccha",
    bg: "#523e34",
    text: "#e0ccbe",
    sub: "#8a6f60",
    main: "#7ec49d",
    caret: "#7ec49d",
    error: "#ff6b6b",
  },
  {
    name: "catppuccin_mocha",
    bg: "#1e1e2e",
    text: "#cdd6f4",
    sub: "#6c7086",
    main: "#f5c2e7",
    caret: "#f5c2e7",
    error: "#f38ba8",
  },
  {
    name: "catppuccin_latte",
    bg: "#eff1f5",
    text: "#4c4f69",
    sub: "#9ca0b0",
    main: "#8839ef",
    caret: "#8839ef",
    error: "#d20f39",
  },
  {
    name: "gmk_red_samurai",
    bg: "#381216",
    text: "#eec45e",
    sub: "#8a3a3a",
    main: "#eec45e",
    caret: "#eec45e",
    error: "#ff4d4d",
  },
  {
    name: "gmk_botanical",
    bg: "#1b1f20",
    text: "#7b9c98",
    sub: "#495e5b",
    main: "#95b5aa",
    caret: "#95b5aa",
    error: "#e06c75",
  },
];

export const KEYBOARD_ROWS = [
  ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]"],
  ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'"],
  ["z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
];
